# DS3/GSE182109 — build the merged raw-count AnnData object

This notebook reconstructs the GSE182109 analysis object from the 44
sample-level 10x Genomics matrix triplets extracted from the GEO RAW
archive.

Every sample must have:

- `<prefix>_matrix.mtx.gz`
- `<prefix>_features.tsv.gz`
- `<prefix>_barcodes.tsv.gz`

The prefix encodes the GEO sample and biological label, for example:

`GSM5518596_rGBM-01-A`

The original pipeline used gene symbols as the feature axis, made duplicate
symbols unique within each sample, appended the sample prefix to each cell
barcode, and concatenated samples with an outer gene join.

## Expected merged object

- 44 samples
- 264,951 cells
- 38,224 genes

## Default paths

Input:

`data/raw/GSE182109/`

Output:

`data/interim/DS3_GSE182109/GSE182109_merged_rawcounts.h5ad`

Override paths with `GLIOMA_PROJECT_ROOT`, `GSE182109_RAW_DIR`, and
`GSE182109_MERGED_H5AD`.

In [1]:
import gc
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc
import scipy.sparse as sp

print("Python:", sys.version)
print("anndata:", ad.__version__)
print("scanpy:", sc.__version__)

Python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]
anndata: 0.12.7
scanpy: 1.11.5

C:\Users\AmirSilco\AppData\Local\Temp\ipykernel_9304\3863974015.py:16: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print("anndata:", ad.__version__)
C:\Users\AmirSilco\AppData\Local\Temp\ipykernel_9304\3863974015.py:17: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  print("scanpy:", sc.__version__)

In [2]:
def find_repository_root(start: Path) -> Path:
    start = start.expanduser().resolve()
    for candidate in (start, *start.parents):
        if (candidate / "README.md").exists() and (candidate / "code").exists():
            return candidate
    return start


PROJECT_ROOT = Path(
    os.environ.get("GLIOMA_PROJECT_ROOT", find_repository_root(Path.cwd()))
).expanduser().resolve()

RAW_DIR = Path(
    os.environ.get(
        "GSE182109_RAW_DIR",
        PROJECT_ROOT / "data" / "raw" / "GSE182109",
    )
).expanduser().resolve()

OUTPUT_H5AD = Path(
    os.environ.get(
        "GSE182109_MERGED_H5AD",
        PROJECT_ROOT
        / "data"
        / "interim"
        / "DS3_GSE182109"
        / "GSE182109_merged_rawcounts.h5ad",
    )
).expanduser().resolve()

AUDIT_DIR = (
    PROJECT_ROOT / "results" / "qc" / "DS3_GSE182109" / "00a_build"
)

EXPECTED_N_SAMPLES = 44
EXPECTED_OUTPUT_SHAPE = (264_951, 38_224)

OUTPUT_H5AD.parent.mkdir(parents=True, exist_ok=True)
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("RAW directory:", RAW_DIR)
print("Output:", OUTPUT_H5AD)

if not RAW_DIR.exists():
    raise FileNotFoundError(
        f"GSE182109 RAW directory not found: {RAW_DIR}\n"
        "Extract the 10x files there or set GSE182109_RAW_DIR."
    )

Project root: C:\Users\AmirSilco\Documents\GitHub\glioma-cnv-single-cell-atlas
RAW directory: C:\Users\AmirSilco\Documents\GitHub\glioma-cnv-single-cell-atlas\data\raw\GSE182109
Output: C:\Users\AmirSilco\Documents\GitHub\glioma-cnv-single-cell-atlas\data\interim\DS3_GSE182109\GSE182109_merged_rawcounts.h5ad

In [3]:
PREFIX_PATTERN = re.compile(
    r"^(GSM\d+)_(LGG|ndGBM|rGBM)-([^-]+)(?:-(.+))?$"
)


def parse_sample_metadata(prefix: str) -> dict:
    match = PREFIX_PATTERN.match(prefix)
    if match is None:
        raise ValueError(
            f"Unexpected GSE182109 sample prefix: {prefix!r}. "
            "Expected GSM..._<LGG|ndGBM|rGBM>-<patient>[-<region>]."
        )

    gsm, group, patient, region = match.groups()
    return {
        "gsm": gsm,
        "sample": prefix,
        "sample_id": prefix,
        "group": group,
        "patient": patient,
        "region": region if region is not None else "",
        "sample_key": prefix,
        "geo_id": "GSE182109",
        "core_dataset": "DS3_GSE182109",
    }


def discover_complete_10x_triplets(raw_dir: Path) -> list[dict]:
    matrix_paths = sorted(raw_dir.glob("GSM*_matrix.mtx.gz"))
    if not matrix_paths:
        raise FileNotFoundError(
            f"No files matching GSM*_matrix.mtx.gz were found in {raw_dir}"
        )

    records = []
    for matrix_path in matrix_paths:
        prefix = matrix_path.name.removesuffix("_matrix.mtx.gz")
        features_path = raw_dir / f"{prefix}_features.tsv.gz"
        barcodes_path = raw_dir / f"{prefix}_barcodes.tsv.gz"

        missing = [
            path.name
            for path in (features_path, barcodes_path)
            if not path.exists()
        ]
        if missing:
            raise FileNotFoundError(
                f"Incomplete 10x triplet for {prefix}: missing {missing}"
            )

        metadata = parse_sample_metadata(prefix)
        records.append(
            {
                "prefix": prefix,
                "matrix_path": matrix_path,
                "features_path": features_path,
                "barcodes_path": barcodes_path,
                **metadata,
            }
        )

    if len(records) != EXPECTED_N_SAMPLES:
        raise AssertionError(
            f"Expected {EXPECTED_N_SAMPLES} complete sample triplets, "
            f"observed {len(records)}."
        )

    return records


input_records = discover_complete_10x_triplets(RAW_DIR)

inventory = pd.DataFrame(
    [
        {
            "prefix": record["prefix"],
            "gsm": record["gsm"],
            "group": record["group"],
            "patient": record["patient"],
            "region": record["region"],
            "matrix_file": record["matrix_path"].name,
            "features_file": record["features_path"].name,
            "barcodes_file": record["barcodes_path"].name,
        }
        for record in input_records
    ]
)
inventory.to_csv(
    AUDIT_DIR / "GSE182109_input_10x_inventory.tsv",
    sep="\t",
    index=False,
)
inventory

,prefix,gsm,group,patient,region,matrix_file,features_file,barcodes_file
0,GSM5518596_rGBM-01-A,GSM5518596,rGBM,01,A,GSM5518596_rGBM-01-A_matrix.mtx.gz,GSM5518596_rGBM-01-A_features.tsv.gz,GSM5518596_rGBM-01-A_barcodes.tsv.gz
1,GSM5518597_rGBM-01-B,GSM5518597,rGBM,01,B,GSM5518597_rGBM-01-B_matrix.mtx.gz,GSM5518597_rGBM-01-B_features.tsv.gz,GSM5518597_rGBM-01-B_barcodes.tsv.gz
2,GSM5518598_rGBM-01-C,GSM5518598,rGBM,01,C,GSM5518598_rGBM-01-C_matrix.mtx.gz,GSM5518598_rGBM-01-C_features.tsv.gz,GSM5518598_rGBM-01-C_barcodes.tsv.gz
3,GSM5518599_rGBM-01-D,GSM5518599,rGBM,01,D,GSM5518599_rGBM-01-D_matrix.mtx.gz,GSM5518599_rGBM-01-D_features.tsv.gz,GSM5518599_rGBM-01-D_barcodes.tsv.gz
4,GSM5518600_ndGBM-01-A,GSM5518600,ndGBM,01,A,GSM5518600_ndGBM-01-A_matrix.mtx.gz,GSM5518600_ndGBM-01-A_features.tsv.gz,GSM5518600_ndGBM-01-A_barcodes.tsv.gz
5,GSM5518601_ndGBM-01-C,GSM5518601,ndGBM,01,C,GSM5518601_ndGBM-01-C_matrix.mtx.gz,GSM5518601_ndGBM-01-C_features.tsv.gz,GSM5518601_ndGBM-01-C_barcodes.tsv.gz
6,GSM5518602_ndGBM-01-D,GSM5518602,ndGBM,01,D,GSM5518602_ndGBM-01-D_matrix.mtx.gz,GSM5518602_ndGBM-01-D_features.tsv.gz,GSM5518602_ndGBM-01-D_barcodes.tsv.gz
7,GSM5518603_ndGBM-01-F,GSM5518603,ndGBM,01,F,GSM5518603_ndGBM-01-F_matrix.mtx.gz,GSM5518603_ndGBM-01-F_features.tsv.gz,GSM5518603_ndGBM-01-F_barcodes.tsv.gz
8,GSM5518604_ndGBM-11-A,GSM5518604,ndGBM,11,A,GSM5518604_ndGBM-11-A_matrix.mtx.gz,GSM5518604_ndGBM-11-A_features.tsv.gz,GSM5518604_ndGBM-11-A_barcodes.tsv.gz
9,GSM5518605_ndGBM-11-B,GSM5518605,ndGBM,11,B,GSM5518605_ndGBM-11-B_matrix.mtx.gz,GSM5518605_ndGBM-11-B_features.tsv.gz,GSM5518605_ndGBM-11-B_barcodes.tsv.gz
10,GSM5518606_ndGBM-11-C,GSM5518606,ndGBM,11,C,GSM5518606_ndGBM-11-C_matrix.mtx.gz,GSM5518606_ndGBM-11-C_features.tsv.gz,GSM5518606_ndGBM-11-C_barcodes.tsv.gz
11,GSM5518607_ndGBM-11-D,GSM5518607,ndGBM,11,D,GSM5518607_ndGBM-11-D_matrix.mtx.gz,GSM5518607_ndGBM-11-D_features.tsv.gz,GSM5518607_ndGBM-11-D_barcodes.tsv.gz
12,GSM5518608_ndGBM-02-1,GSM5518608,ndGBM,02,1,GSM5518608_ndGBM-02-1_matrix.mtx.gz,GSM5518608_ndGBM-02-1_features.tsv.gz,GSM5518608_ndGBM-02-1_barcodes.tsv.gz
13,GSM5518609_ndGBM-02-2,GSM5518609,ndGBM,02,2,GSM5518609_ndGBM-02-2_matrix.mtx.gz,GSM5518609_ndGBM-02-2_features.tsv.gz,GSM5518609_ndGBM-02-2_barcodes.tsv.gz
14,GSM5518610_ndGBM-02-4,GSM5518610,ndGBM,02,4,GSM5518610_ndGBM-02-4_matrix.mtx.gz,GSM5518610_ndGBM-02-4_features.tsv.gz,GSM5518610_ndGBM-02-4_barcodes.tsv.gz
15,GSM5518611_ndGBM-02-5,GSM5518611,ndGBM,02,5,GSM5518611_ndGBM-02-5_matrix.mtx.gz,GSM5518611_ndGBM-02-5_features.tsv.gz,GSM5518611_ndGBM-02-5_barcodes.tsv.gz
16,GSM5518612_rGBM-02-2,GSM5518612,rGBM,02,2,GSM5518612_rGBM-02-2_matrix.mtx.gz,GSM5518612_rGBM-02-2_features.tsv.gz,GSM5518612_rGBM-02-2_barcodes.tsv.gz
17,GSM5518613_rGBM-02-3,GSM5518613,rGBM,02,3,GSM5518613_rGBM-02-3_matrix.mtx.gz,GSM5518613_rGBM-02-3_features.tsv.gz,GSM5518613_rGBM-02-3_barcodes.tsv.gz
18,GSM5518614_rGBM-02-4,GSM5518614,rGBM,02,4,GSM5518614_rGBM-02-4_matrix.mtx.gz,GSM5518614_rGBM-02-4_features.tsv.gz,GSM5518614_rGBM-02-4_barcodes.tsv.gz
19,GSM5518615_rGBM-02-5,GSM5518615,rGBM,02,5,GSM5518615_rGBM-02-5_matrix.mtx.gz,GSM5518615_rGBM-02-5_features.tsv.gz,GSM5518615_rGBM-02-5_barcodes.tsv.gz
20,GSM5518616_rGBM-03-1,GSM5518616,rGBM,03,1,GSM5518616_rGBM-03-1_matrix.mtx.gz,GSM5518616_rGBM-03-1_features.tsv.gz,GSM5518616_rGBM-03-1_barcodes.tsv.gz
21,GSM5518617_rGBM-03-2,GSM5518617,rGBM,03,2,GSM5518617_rGBM-03-2_matrix.mtx.gz,GSM5518617_rGBM-03-2_features.tsv.gz,GSM5518617_rGBM-03-2_barcodes.tsv.gz
22,GSM5518618_rGBM-03-3,GSM5518618,rGBM,03,3,GSM5518618_rGBM-03-3_matrix.mtx.gz,GSM5518618_rGBM-03-3_features.tsv.gz,GSM5518618_rGBM-03-3_barcodes.tsv.gz
23,GSM5518619_rGBM-04-1,GSM5518619,rGBM,04,1,GSM5518619_rGBM-04-1_matrix.mtx.gz,GSM5518619_rGBM-04-1_features.tsv.gz,GSM5518619_rGBM-04-1_barcodes.tsv.gz
24,GSM5518620_rGBM-04-2,GSM5518620,rGBM,04,2,GSM5518620_rGBM-04-2_matrix.mtx.gz,GSM5518620_rGBM-04-2_features.tsv.gz,GSM5518620_rGBM-04-2_barcodes.tsv.gz
25,GSM5518621_rGBM-04-3,GSM5518621,rGBM,04,3,GSM5518621_rGBM-04-3_matrix.mtx.gz,GSM5518621_rGBM-04-3_features.tsv.gz,GSM5518621_rGBM-04-3_barcodes.tsv.gz
26,GSM5518622_rGBM-04-4,GSM5518622,rGBM,04,4,GSM5518622_rGBM-04-4_matrix.mtx.gz,GSM5518622_rGBM-04-4_features.tsv.gz,GSM5518622_rGBM-04-4_barcodes.tsv.gz
27,GSM5518623_ndGBM-03-1,GSM5518623,ndGBM,03,1,GSM5518623_ndGBM-03-1_matrix.mtx.gz,GSM5518623_ndGBM-03-1_features.tsv.gz,GSM5518623_ndGBM-03-1_barcodes.tsv.gz
28,GSM5518624_ndGBM-03-2,GSM5518624,ndGBM,03,2,GSM5518624_ndGBM-03-2_matrix.mtx.gz,GSM5518624_ndGBM-03-2_features.tsv.gz,GSM5518624_ndGBM-03-2_barcodes.tsv.gz
29,GSM5518625_ndGBM-03-3,GSM5518625,ndGBM,03,3,GSM5518625_ndGBM-03-3_matrix.mtx.gz,GSM5518625_ndGBM-03-3_features.tsv.gz,GSM5518625_ndGBM-03-3_barcodes.tsv.gz
30,GSM5518626_rGBM-05-1,GSM5518626,rGBM,05,1,GSM5518626_rGBM-05-1_matrix.mtx.gz,GSM5518626_rGBM-05-1_features.tsv.gz,GSM5518626_rGBM-05-1_barcodes.tsv.gz
31,GSM5518627_rGBM-05-2,GSM5518627,rGBM,05,2,GSM5518627_rGBM-05-2_matrix.mtx.gz,GSM5518627_rGBM-05-2_features.tsv.gz,GSM5518627_rGBM-05-2_barcodes.tsv.gz
32,GSM5518628_rGBM-05-3,GSM5518628,rGBM,05,3,GSM5518628_rGBM-05-3_matrix.mtx.gz,GSM5518628_rGBM-05-3_features.tsv.gz,GSM5518628_rGBM-05-3_barcodes.tsv.gz
33,GSM5518629_ndGBM-10,GSM5518629,ndGBM,10,,GSM5518629_ndGBM-10_matrix.mtx.gz,GSM5518629_ndGBM-10_features.tsv.gz,GSM5518629_ndGBM-10_barcodes.tsv.gz
34,GSM5518630_LGG-04-1,GSM5518630,LGG,04,1,GSM5518630_LGG-04-1_matrix.mtx.gz,GSM5518630_LGG-04-1_features.tsv.gz,GSM5518630_LGG-04-1_barcodes.tsv.gz
35,GSM5518631_LGG-04-2,GSM5518631,LGG,04,2,GSM5518631_LGG-04-2_matrix.mtx.gz,GSM5518631_LGG-04-2_features.tsv.gz,GSM5518631_LGG-04-2_barcodes.tsv.gz
36,GSM5518632_LGG-04-3,GSM5518632,LGG,04,3,GSM5518632_LGG-04-3_matrix.mtx.gz,GSM5518632_LGG-04-3_features.tsv.gz,GSM5518632_LGG-04-3_barcodes.tsv.gz
37,GSM5518633_ndGBM-04,GSM5518633,ndGBM,04,,GSM5518633_ndGBM-04_matrix.mtx.gz,GSM5518633_ndGBM-04_features.tsv.gz,GSM5518633_ndGBM-04_barcodes.tsv.gz
38,GSM5518634_ndGBM-05,GSM5518634,ndGBM,05,,GSM5518634_ndGBM-05_matrix.mtx.gz,GSM5518634_ndGBM-05_features.tsv.gz,GSM5518634_ndGBM-05_barcodes.tsv.gz
39,GSM5518635_ndGBM-06,GSM5518635,ndGBM,06,,GSM5518635_ndGBM-06_matrix.mtx.gz,GSM5518635_ndGBM-06_features.tsv.gz,GSM5518635_ndGBM-06_barcodes.tsv.gz
40,GSM5518636_ndGBM-07,GSM5518636,ndGBM,07,,GSM5518636_ndGBM-07_matrix.mtx.gz,GSM5518636_ndGBM-07_features.tsv.gz,GSM5518636_ndGBM-07_barcodes.tsv.gz
41,GSM5518637_ndGBM-08,GSM5518637,ndGBM,08,,GSM5518637_ndGBM-08_matrix.mtx.gz,GSM5518637_ndGBM-08_features.tsv.gz,GSM5518637_ndGBM-08_barcodes.tsv.gz
42,GSM5518638_LGG-03,GSM5518638,LGG,03,,GSM5518638_LGG-03_matrix.mtx.gz,GSM5518638_LGG-03_features.tsv.gz,GSM5518638_LGG-03_barcodes.tsv.gz
43,GSM5518639_ndGBM-09,GSM5518639,ndGBM,09,,GSM5518639_ndGBM-09_matrix.mtx.gz,GSM5518639_ndGBM-09_features.tsv.gz,GSM5518639_ndGBM-09_barcodes.tsv.gz

In [4]:
def matrix_values(matrix):
    return matrix.data if sp.issparse(matrix) else np.asarray(matrix).ravel()


def assert_raw_counts(matrix, label: str):
    values = matrix_values(matrix)
    if values.size == 0:
        raise ValueError(f"{label} has no nonzero values.")
    if not np.isfinite(values).all():
        raise ValueError(f"{label} contains non-finite values.")
    if np.any(values < 0):
        raise ValueError(f"{label} contains negative values.")
    if not np.equal(values, np.floor(values)).all():
        raise ValueError(f"{label} is not an integer raw-count matrix.")


def read_sample(record: dict) -> ad.AnnData:
    sample = sc.read_10x_mtx(
        RAW_DIR,
        prefix=record["prefix"] + "_",
        var_names="gene_symbols",
        make_unique=False,
        cache=False,
        gex_only=True,
    )

    if sample.n_obs == 0 or sample.n_vars == 0:
        raise ValueError(
            f"{record['prefix']}: the parsed 10x object is empty."
        )

    original_symbols = sample.var_names.astype(str)
    sample.var["feature_name_original"] = original_symbols
    sample.var_names_make_unique()

    if not sample.var_names.is_unique:
        raise AssertionError(
            f"{record['prefix']}: gene symbols remain duplicated."
        )

    if sp.issparse(sample.X):
        sample.X = sample.X.tocsr().astype(np.float32, copy=False)
    else:
        sample.X = sp.csr_matrix(
            np.asarray(sample.X, dtype=np.float32)
        )

    assert_raw_counts(sample.X, f"{record['prefix']}: adata.X")

    original_barcodes = sample.obs_names.astype(str)
    sample.obs["cell_barcode"] = original_barcodes
    sample.obs_names = pd.Index(
        [
            f"{barcode}-{record['prefix']}"
            for barcode in original_barcodes
        ],
        name="cell_id",
    )

    if not sample.obs_names.is_unique:
        raise AssertionError(
            f"{record['prefix']}: cell identifiers are not unique."
        )

    for key in (
        "gsm",
        "sample",
        "sample_id",
        "group",
        "patient",
        "region",
        "sample_key",
        "geo_id",
        "core_dataset",
    ):
        sample.obs[key] = record[key]

    sample.uns["source_prefix"] = record["prefix"]
    sample.uns["source_geo_accession"] = record["gsm"]
    return sample


sample_objects = []
sample_summary_rows = []
var_frames = []

for index, record in enumerate(input_records, start=1):
    print(
        f"[{index}/{len(input_records)}] Loading "
        f"{record['prefix']}"
    )
    sample = read_sample(record)

    sample_summary_rows.append(
        {
            "gsm": record["gsm"],
            "sample": record["sample"],
            "group": record["group"],
            "patient": record["patient"],
            "region": record["region"],
            "cells": int(sample.n_obs),
            "genes": int(sample.n_vars),
            "total_counts": int(sample.X.sum()),
            "maximum_count": int(sample.X.max()),
        }
    )

    var_frame = sample.var.copy()
    var_frame["var_name"] = sample.var_names.astype(str)
    var_frame["source_sample"] = record["sample"]
    var_frames.append(var_frame.reset_index(drop=True))

    sample_objects.append(sample)
    print(sample)
    gc.collect()

sample_summary = pd.DataFrame(sample_summary_rows)
sample_summary.to_csv(
    AUDIT_DIR / "GSE182109_raw_build_sample_summary.tsv",
    sep="\t",
    index=False,
)
sample_summary

[1/44] Loading GSM5518596_rGBM-01-A

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 4594 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[2/44] Loading GSM5518597_rGBM-01-B

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 11716 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[3/44] Loading GSM5518598_rGBM-01-C

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 5965 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[4/44] Loading GSM5518599_rGBM-01-D

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 6434 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[5/44] Loading GSM5518600_ndGBM-01-A

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 5018 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[6/44] Loading GSM5518601_ndGBM-01-C

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 10342 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[7/44] Loading GSM5518602_ndGBM-01-D

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 9338 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[8/44] Loading GSM5518603_ndGBM-01-F

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 5773 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[9/44] Loading GSM5518604_ndGBM-11-A

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 805 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[10/44] Loading GSM5518605_ndGBM-11-B

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 544 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[11/44] Loading GSM5518606_ndGBM-11-C

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 2929 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[12/44] Loading GSM5518607_ndGBM-11-D

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 1530 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[13/44] Loading GSM5518608_ndGBM-02-1

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 9027 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[14/44] Loading GSM5518609_ndGBM-02-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 6854 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[15/44] Loading GSM5518610_ndGBM-02-4

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 6518 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[16/44] Loading GSM5518611_ndGBM-02-5

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 8748 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[17/44] Loading GSM5518612_rGBM-02-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 2658 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[18/44] Loading GSM5518613_rGBM-02-3

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 10947 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[19/44] Loading GSM5518614_rGBM-02-4

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 1112 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[20/44] Loading GSM5518615_rGBM-02-5

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 11967 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[21/44] Loading GSM5518616_rGBM-03-1

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 4311 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[22/44] Loading GSM5518617_rGBM-03-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 1992 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[23/44] Loading GSM5518618_rGBM-03-3

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 4748 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[24/44] Loading GSM5518619_rGBM-04-1

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 6857 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[25/44] Loading GSM5518620_rGBM-04-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 7081 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[26/44] Loading GSM5518621_rGBM-04-3

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 8236 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[27/44] Loading GSM5518622_rGBM-04-4

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 7296 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[28/44] Loading GSM5518623_ndGBM-03-1

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 4001 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[29/44] Loading GSM5518624_ndGBM-03-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3076 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[30/44] Loading GSM5518625_ndGBM-03-3

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3550 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[31/44] Loading GSM5518626_rGBM-05-1

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 5258 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[32/44] Loading GSM5518627_rGBM-05-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3454 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[33/44] Loading GSM5518628_rGBM-05-3

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 2130 × 33538
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[34/44] Loading GSM5518629_ndGBM-10

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 11190 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[35/44] Loading GSM5518630_LGG-04-1

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 7009 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[36/44] Loading GSM5518631_LGG-04-2

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3052 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[37/44] Loading GSM5518632_LGG-04-3

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 7129 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[38/44] Loading GSM5518633_ndGBM-04

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 8593 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[39/44] Loading GSM5518634_ndGBM-05

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 8267 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[40/44] Loading GSM5518635_ndGBM-06

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3884 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[41/44] Loading GSM5518636_ndGBM-07

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 10304 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[42/44] Loading GSM5518637_ndGBM-08

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 6139 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[43/44] Loading GSM5518638_LGG-03

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 8796 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'
[44/44] Loading GSM5518639_ndGBM-09

C:\Users\AmirSilco\.conda\envs\glioma-cnv-atlas\Lib\site-packages\anndata\_core\anndata.py:1808: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 5779 × 36601
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
    uns: 'source_prefix', 'source_geo_accession'

,gsm,sample,group,patient,region,cells,genes,total_counts,maximum_count
0,GSM5518596,GSM5518596_rGBM-01-A,rGBM,01,A,4594,36601,38426920,8278
1,GSM5518597,GSM5518597_rGBM-01-B,rGBM,01,B,11716,36601,73003648,11072
2,GSM5518598,GSM5518598_rGBM-01-C,rGBM,01,C,5965,36601,36808184,2121
3,GSM5518599,GSM5518599_rGBM-01-D,rGBM,01,D,6434,36601,52386784,8054
4,GSM5518600,GSM5518600_ndGBM-01-A,ndGBM,01,A,5018,33538,39899752,4495
5,GSM5518601,GSM5518601_ndGBM-01-C,ndGBM,01,C,10342,36601,66742616,6407
6,GSM5518602,GSM5518602_ndGBM-01-D,ndGBM,01,D,9338,36601,51700884,2049
7,GSM5518603,GSM5518603_ndGBM-01-F,ndGBM,01,F,5773,36601,19030740,2444
8,GSM5518604,GSM5518604_ndGBM-11-A,ndGBM,11,A,805,36601,1573918,3008
9,GSM5518605,GSM5518605_ndGBM-11-B,ndGBM,11,B,544,36601,1103131,3710
10,GSM5518606,GSM5518606_ndGBM-11-C,ndGBM,11,C,2929,36601,7920395,3211
11,GSM5518607,GSM5518607_ndGBM-11-D,ndGBM,11,D,1530,36601,2707315,2445
12,GSM5518608,GSM5518608_ndGBM-02-1,ndGBM,02,1,9027,36601,60760584,5602
13,GSM5518609,GSM5518609_ndGBM-02-2,ndGBM,02,2,6854,33538,33515454,4428
14,GSM5518610,GSM5518610_ndGBM-02-4,ndGBM,02,4,6518,36601,37418744,6624
15,GSM5518611,GSM5518611_ndGBM-02-5,ndGBM,02,5,8748,36601,37347588,7419
16,GSM5518612,GSM5518612_rGBM-02-2,rGBM,02,2,2658,33538,29760436,29022
17,GSM5518613,GSM5518613_rGBM-02-3,rGBM,02,3,10947,33538,83766928,32644
18,GSM5518614,GSM5518614_rGBM-02-4,rGBM,02,4,1112,33538,7656963,15456
19,GSM5518615,GSM5518615_rGBM-02-5,rGBM,02,5,11967,33538,84658688,25471
20,GSM5518616,GSM5518616_rGBM-03-1,rGBM,03,1,4311,33538,39858592,6816
21,GSM5518617,GSM5518617_rGBM-03-2,rGBM,03,2,1992,33538,22769208,6916
22,GSM5518618,GSM5518618_rGBM-03-3,rGBM,03,3,4748,33538,43936576,4627
23,GSM5518619,GSM5518619_rGBM-04-1,rGBM,04,1,6857,33538,89029912,6625
24,GSM5518620,GSM5518620_rGBM-04-2,rGBM,04,2,7081,33538,83212768,18962
25,GSM5518621,GSM5518621_rGBM-04-3,rGBM,04,3,8236,33538,90852432,6026
26,GSM5518622,GSM5518622_rGBM-04-4,rGBM,04,4,7296,33538,96356416,10654
27,GSM5518623,GSM5518623_ndGBM-03-1,ndGBM,03,1,4001,33538,52765704,3603
28,GSM5518624,GSM5518624_ndGBM-03-2,ndGBM,03,2,3076,33538,17666512,6333
29,GSM5518625,GSM5518625_ndGBM-03-3,ndGBM,03,3,3550,33538,45713272,8036
30,GSM5518626,GSM5518626_rGBM-05-1,rGBM,05,1,5258,33538,54031416,3749
31,GSM5518627,GSM5518627_rGBM-05-2,rGBM,05,2,3454,33538,51550584,5580
32,GSM5518628,GSM5518628_rGBM-05-3,rGBM,05,3,2130,33538,26233832,13076
33,GSM5518629,GSM5518629_ndGBM-10,ndGBM,10,,11190,36601,25726764,1161
34,GSM5518630,GSM5518630_LGG-04-1,LGG,04,1,7009,36601,58506920,2881
35,GSM5518631,GSM5518631_LGG-04-2,LGG,04,2,3052,36601,34958332,4036
36,GSM5518632,GSM5518632_LGG-04-3,LGG,04,3,7129,36601,73879240,2982
37,GSM5518633,GSM5518633_ndGBM-04,ndGBM,04,,8593,36601,100942432,6988
38,GSM5518634,GSM5518634_ndGBM-05,ndGBM,05,,8267,36601,79387392,10476
39,GSM5518635,GSM5518635_ndGBM-06,ndGBM,06,,3884,36601,35862200,7207
40,GSM5518636,GSM5518636_ndGBM-07,ndGBM,07,,10304,36601,90037088,27215
41,GSM5518637,GSM5518637_ndGBM-08,ndGBM,08,,6139,36601,78613992,5189
42,GSM5518638,GSM5518638_LGG-03,LGG,03,,8796,36601,81258992,3987
43,GSM5518639,GSM5518639_ndGBM-09,ndGBM,09,,5779,36601,52817728,19826

In [5]:
adata_merged = ad.concat(
    sample_objects,
    axis="obs",
    join="outer",
    merge="first",
    index_unique=None,
    fill_value=0,
    pairwise=False,
)

if not adata_merged.obs_names.is_unique:
    raise AssertionError("Merged cell identifiers are not unique.")
if adata_merged.shape != EXPECTED_OUTPUT_SHAPE:
    raise AssertionError(
        "The GSE182109 merge did not reproduce the historical object. "
        f"Expected {EXPECTED_OUTPUT_SHAPE}, observed {adata_merged.shape}. "
        "Inspect the sample inventory and per-sample summary."
    )
if not sp.issparse(adata_merged.X):
    adata_merged.X = sp.csr_matrix(adata_merged.X)
else:
    adata_merged.X = adata_merged.X.tocsr()

assert_raw_counts(adata_merged.X, "merged adata.X")

print("Merged object:", adata_merged)
print(adata_merged.obs["group"].value_counts())

Merged object: AnnData object with n_obs × n_vars = 264951 × 38224
    obs: 'cell_barcode', 'gsm', 'sample', 'sample_id', 'group', 'patient', 'region', 'sample_key', 'geo_id', 'core_dataset'
    var: 'gene_ids', 'feature_types', 'feature_name_original'
group
ndGBM    132209
rGBM     106756
LGG       25986
Name: count, dtype: int64

In [6]:
# Reconstruct a complete feature-metadata table across the outer gene union.
# Conflicting annotations are audited; the first non-empty value is retained.
all_var = pd.concat(var_frames, ignore_index=True)

metadata_columns = [
    column
    for column in ("gene_ids", "feature_types", "feature_name_original")
    if column in all_var.columns
]

conflict_rows = []
consolidated = pd.DataFrame(index=adata_merged.var_names)

for column in metadata_columns:
    values_by_gene = (
        all_var[["var_name", column]]
        .dropna()
        .assign(**{column: lambda frame: frame[column].astype(str)})
    )
    values_by_gene = values_by_gene[
        values_by_gene[column].str.strip() != ""
    ]

    grouped = values_by_gene.groupby("var_name", sort=False)[column]
    consolidated[column] = grouped.first().reindex(
        adata_merged.var_names
    )

    nunique = grouped.nunique()
    conflicting_genes = nunique[nunique > 1].index
    for gene in conflicting_genes:
        observed_values = sorted(
            values_by_gene.loc[
                values_by_gene["var_name"] == gene,
                column,
            ].unique().tolist()
        )
        conflict_rows.append(
            {
                "var_name": gene,
                "field": column,
                "observed_values": " | ".join(observed_values),
            }
        )

# Preserve any metadata already populated by AnnData concat.
for column in adata_merged.var.columns:
    if column not in consolidated:
        consolidated[column] = adata_merged.var[column]

adata_merged.var = consolidated

conflict_table = pd.DataFrame(
    conflict_rows,
    columns=["var_name", "field", "observed_values"],
)
conflict_table.to_csv(
    AUDIT_DIR / "GSE182109_feature_metadata_conflicts.tsv",
    sep="\t",
    index=False,
)

adata_merged.uns["dataset_id"] = "DS3_GSE182109"
adata_merged.uns["geo_accession"] = "GSE182109"
adata_merged.uns["build_timestamp"] = datetime.now().isoformat(
    timespec="seconds"
)
adata_merged.uns["source_sample_count"] = EXPECTED_N_SAMPLES
adata_merged.uns["feature_join"] = "outer"
adata_merged.uns["feature_metadata_conflict_count"] = int(
    conflict_table.shape[0]
)

build_summary = {
    "dataset_id": "DS3_GSE182109",
    "geo_accession": "GSE182109",
    "n_samples": int(adata_merged.obs["sample"].nunique()),
    "n_cells": int(adata_merged.n_obs),
    "n_genes": int(adata_merged.n_vars),
    "matrix_format": type(adata_merged.X).__name__,
    "matrix_dtype": str(adata_merged.X.dtype),
    "feature_metadata_conflicts": int(conflict_table.shape[0]),
    "output_h5ad": str(OUTPUT_H5AD),
}

with open(
    AUDIT_DIR / "GSE182109_raw_build_summary.json",
    "w",
    encoding="utf-8",
) as handle:
    json.dump(build_summary, handle, indent=2)

print(build_summary)

{'dataset_id': 'DS3_GSE182109', 'geo_accession': 'GSE182109', 'n_samples': 44, 'n_cells': 264951, 'n_genes': 38224, 'matrix_format': 'csr_matrix', 'matrix_dtype': 'float32', 'feature_metadata_conflicts': 349, 'output_h5ad': 'C:\\Users\\AmirSilco\\Documents\\GitHub\\glioma-cnv-single-cell-atlas\\data\\interim\\DS3_GSE182109\\GSE182109_merged_rawcounts.h5ad'}

In [8]:
from pathlib import Path

import scanpy as sc


# ------------------------------------------------------------------
# Save the merged DS3 AnnData object atomically
# ------------------------------------------------------------------
OUTPUT_H5AD = Path(OUTPUT_H5AD)
OUTPUT_H5AD.parent.mkdir(parents=True, exist_ok=True)

temporary_output = OUTPUT_H5AD.with_name(
    f"{OUTPUT_H5AD.stem}.temporary{OUTPUT_H5AD.suffix}"
)

# Remove a stale temporary file from an interrupted run.
if temporary_output.exists():
    temporary_output.unlink()

adata_merged.write_h5ad(
    temporary_output,
    compression="gzip",
)

if not temporary_output.exists():
    raise FileNotFoundError(
        f"Temporary output was not created: {temporary_output}"
    )

temporary_output.replace(OUTPUT_H5AD)

if not OUTPUT_H5AD.exists():
    raise FileNotFoundError(
        f"Final output was not created: {OUTPUT_H5AD}"
    )


# ------------------------------------------------------------------
# Reopen and validate without using a context manager
# ------------------------------------------------------------------
check = sc.read_h5ad(
    OUTPUT_H5AD,
    backed="r",
)

try:
    observed_shape = tuple(check.shape)
    expected_shape = tuple(EXPECTED_OUTPUT_SHAPE)

    if observed_shape != expected_shape:
        raise AssertionError(
            "Saved-file validation failed: "
            f"expected {expected_shape}, observed {observed_shape}"
        )

    if check.obs_names.has_duplicates:
        raise AssertionError(
            "Saved output contains duplicated cell identifiers."
        )

    if check.n_obs == 0:
        raise AssertionError(
            "Saved output contains zero cells."
        )

    if check.n_vars == 0:
        raise AssertionError(
            "Saved output contains zero features."
        )

    # Validate important annotations when present in memory.
    for column in (
        "sample_id",
        "sample_key",
        "gsm",
        "group",
        "patient",
        "region",
    ):
        if column in adata_merged.obs.columns:
            if column not in check.obs.columns:
                raise AssertionError(
                    f"Saved output is missing obs[{column!r}]."
                )

    for column in (
        "gene_ids",
        "feature_types",
        "feature_name_original",
    ):
        if column in adata_merged.var.columns:
            if column not in check.var.columns:
                raise AssertionError(
                    f"Saved output is missing var[{column!r}]."
                )

finally:
    check.file.close()


# ------------------------------------------------------------------
# Report successful completion
# ------------------------------------------------------------------
print("Saved and validated:", OUTPUT_H5AD)
print("Validated shape:", expected_shape)

Saved and validated: C:\Users\AmirSilco\Documents\GitHub\glioma-cnv-single-cell-atlas\data\interim\DS3_GSE182109\GSE182109_merged_rawcounts.h5ad
Validated shape: (264951, 38224)